Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Max: 20